---
name: CI Pipeline

on: [push, pull_request]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generator
        run: make generate-embeddedyamls

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.38.0
          args: --timeout 5m0s
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.0'

    - name: Testing build
      run: |
        make build

    - name: Set up QEMU
      if: github.event_name != 'pull_request'
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      if: github.event_name != 'pull_request'
      uses: docker/setup-buildx-action@v1

    - name: Login to quay.io
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1 
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Image
      if: github.event_name != 'pull_request'
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        file: ./Dockerfile
        push: true
        tags: quay.io/danielxlee/knitnet-operator:latest
